/* =========================================================
   mock_data.js — Auto-generated Data for Smart Logistics UI
   Run generate_mock_data.py to update this file.
   ========================================================= */

const UIData = {
    weatherConditions: [
    "clear",
    "cloudy",
    "fog",
    "rain",
    "snow",
    "wind"
],
    trafficLevels: [
    "congested",
    "high",
    "low",
    "moderate"
],
    historicalSummary: [
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "clear",
        "time_bucket": "morning_rush",
        "sample_count": 34,
        "mean_delay_min": 13.39,
        "median_delay_min": 11.39,
        "p90_delay_min": 24.11,
        "p95_delay_min": 29.47,
        "std_delay_min": 6.7,
        "on_time_rate": 0.777,
        "delay_probability": 0.017
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "clear",
        "time_bucket": "midday",
        "sample_count": 55,
        "mean_delay_min": 4.96,
        "median_delay_min": 4.22,
        "p90_delay_min": 8.93,
        "p95_delay_min": 10.91,
        "std_delay_min": 2.48,
        "on_time_rate": 0.917,
        "delay_probability": 0.017
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "clear",
        "time_bucket": "evening_rush",
        "sample_count": 135,
        "mean_delay_min": 11.46,
        "median_delay_min": 9.74,
        "p90_delay_min": 20.62,
        "p95_delay_min": 25.2,
        "std_delay_min": 5.73,
        "on_time_rate": 0.809,
        "delay_probability": 0.017
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "clear",
        "time_bucket": "night",
        "sample_count": 288,
        "mean_delay_min": 4.73,
        "median_delay_min": 4.02,
        "p90_delay_min": 8.51,
        "p95_delay_min": 10.4,
        "std_delay_min": 2.36,
        "on_time_rate": 0.921,
        "delay_probability": 0.017
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "clear",
        "time_bucket": "early_morning",
        "sample_count": 61,
        "mean_delay_min": 4.85,
        "median_delay_min": 4.12,
        "p90_delay_min": 8.72,
        "p95_delay_min": 10.66,
        "std_delay_min": 2.42,
        "on_time_rate": 0.919,
        "delay_probability": 0.017
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "cloudy",
        "time_bucket": "morning_rush",
        "sample_count": 232,
        "mean_delay_min": 13.49,
        "median_delay_min": 11.47,
        "p90_delay_min": 24.28,
        "p95_delay_min": 29.68,
        "std_delay_min": 6.74,
        "on_time_rate": 0.775,
        "delay_probability": 0.033
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "cloudy",
        "time_bucket": "midday",
        "sample_count": 458,
        "mean_delay_min": 2.26,
        "median_delay_min": 1.92,
        "p90_delay_min": 4.07,
        "p95_delay_min": 4.98,
        "std_delay_min": 1.13,
        "on_time_rate": 0.962,
        "delay_probability": 0.033
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "cloudy",
        "time_bucket": "evening_rush",
        "sample_count": 418,
        "mean_delay_min": 15.15,
        "median_delay_min": 12.88,
        "p90_delay_min": 27.28,
        "p95_delay_min": 33.34,
        "std_delay_min": 7.58,
        "on_time_rate": 0.747,
        "delay_probability": 0.033
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "cloudy",
        "time_bucket": "night",
        "sample_count": 324,
        "mean_delay_min": 3.33,
        "median_delay_min": 2.83,
        "p90_delay_min": 5.99,
        "p95_delay_min": 7.32,
        "std_delay_min": 1.66,
        "on_time_rate": 0.945,
        "delay_probability": 0.033
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "cloudy",
        "time_bucket": "early_morning",
        "sample_count": 357,
        "mean_delay_min": 1.09,
        "median_delay_min": 0.92,
        "p90_delay_min": 1.96,
        "p95_delay_min": 2.39,
        "std_delay_min": 0.54,
        "on_time_rate": 0.982,
        "delay_probability": 0.033
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "rain",
        "time_bucket": "morning_rush",
        "sample_count": 173,
        "mean_delay_min": 13.01,
        "median_delay_min": 11.06,
        "p90_delay_min": 23.42,
        "p95_delay_min": 28.63,
        "std_delay_min": 6.51,
        "on_time_rate": 0.783,
        "delay_probability": 0.1
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "rain",
        "time_bucket": "midday",
        "sample_count": 298,
        "mean_delay_min": 7.97,
        "median_delay_min": 6.77,
        "p90_delay_min": 14.34,
        "p95_delay_min": 17.52,
        "std_delay_min": 3.98,
        "on_time_rate": 0.867,
        "delay_probability": 0.1
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "rain",
        "time_bucket": "evening_rush",
        "sample_count": 307,
        "mean_delay_min": 19.54,
        "median_delay_min": 16.61,
        "p90_delay_min": 35.18,
        "p95_delay_min": 42.99,
        "std_delay_min": 9.77,
        "on_time_rate": 0.674,
        "delay_probability": 0.1
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "rain",
        "time_bucket": "night",
        "sample_count": 140,
        "mean_delay_min": 6.14,
        "median_delay_min": 5.22,
        "p90_delay_min": 11.05,
        "p95_delay_min": 13.5,
        "std_delay_min": 3.07,
        "on_time_rate": 0.898,
        "delay_probability": 0.1
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "rain",
        "time_bucket": "early_morning",
        "sample_count": 369,
        "mean_delay_min": 8.2,
        "median_delay_min": 6.97,
        "p90_delay_min": 14.76,
        "p95_delay_min": 18.04,
        "std_delay_min": 4.1,
        "on_time_rate": 0.863,
        "delay_probability": 0.1
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "snow",
        "time_bucket": "morning_rush",
        "sample_count": 275,
        "mean_delay_min": 24.67,
        "median_delay_min": 20.97,
        "p90_delay_min": 44.41,
        "p95_delay_min": 54.28,
        "std_delay_min": 12.34,
        "on_time_rate": 0.589,
        "delay_probability": 0.267
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "snow",
        "time_bucket": "midday",
        "sample_count": 313,
        "mean_delay_min": 16.34,
        "median_delay_min": 13.89,
        "p90_delay_min": 29.42,
        "p95_delay_min": 35.95,
        "std_delay_min": 8.17,
        "on_time_rate": 0.728,
        "delay_probability": 0.267
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "snow",
        "time_bucket": "evening_rush",
        "sample_count": 351,
        "mean_delay_min": 27.64,
        "median_delay_min": 23.49,
        "p90_delay_min": 49.75,
        "p95_delay_min": 60.81,
        "std_delay_min": 13.82,
        "on_time_rate": 0.539,
        "delay_probability": 0.267
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "snow",
        "time_bucket": "night",
        "sample_count": 160,
        "mean_delay_min": 17.05,
        "median_delay_min": 14.49,
        "p90_delay_min": 30.69,
        "p95_delay_min": 37.51,
        "std_delay_min": 8.53,
        "on_time_rate": 0.716,
        "delay_probability": 0.267
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "snow",
        "time_bucket": "early_morning",
        "sample_count": 385,
        "mean_delay_min": 14.35,
        "median_delay_min": 12.19,
        "p90_delay_min": 25.82,
        "p95_delay_min": 31.56,
        "std_delay_min": 7.17,
        "on_time_rate": 0.761,
        "delay_probability": 0.267
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "fog",
        "time_bucket": "morning_rush",
        "sample_count": 72,
        "mean_delay_min": 20.63,
        "median_delay_min": 17.54,
        "p90_delay_min": 37.14,
        "p95_delay_min": 45.39,
        "std_delay_min": 10.32,
        "on_time_rate": 0.656,
        "delay_probability": 0.15
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "fog",
        "time_bucket": "midday",
        "sample_count": 477,
        "mean_delay_min": 12.54,
        "median_delay_min": 10.66,
        "p90_delay_min": 22.58,
        "p95_delay_min": 27.59,
        "std_delay_min": 6.27,
        "on_time_rate": 0.791,
        "delay_probability": 0.15
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "fog",
        "time_bucket": "evening_rush",
        "sample_count": 47,
        "mean_delay_min": 18.92,
        "median_delay_min": 16.08,
        "p90_delay_min": 34.06,
        "p95_delay_min": 41.63,
        "std_delay_min": 9.46,
        "on_time_rate": 0.685,
        "delay_probability": 0.15
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "fog",
        "time_bucket": "night",
        "sample_count": 436,
        "mean_delay_min": 8.43,
        "median_delay_min": 7.16,
        "p90_delay_min": 15.17,
        "p95_delay_min": 18.54,
        "std_delay_min": 4.21,
        "on_time_rate": 0.86,
        "delay_probability": 0.15
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "fog",
        "time_bucket": "early_morning",
        "sample_count": 495,
        "mean_delay_min": 9.1,
        "median_delay_min": 7.74,
        "p90_delay_min": 16.38,
        "p95_delay_min": 20.02,
        "std_delay_min": 4.55,
        "on_time_rate": 0.848,
        "delay_probability": 0.15
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "wind",
        "time_bucket": "morning_rush",
        "sample_count": 32,
        "mean_delay_min": 10.5,
        "median_delay_min": 8.93,
        "p90_delay_min": 18.91,
        "p95_delay_min": 23.11,
        "std_delay_min": 5.25,
        "on_time_rate": 0.825,
        "delay_probability": 0.067
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "wind",
        "time_bucket": "midday",
        "sample_count": 467,
        "mean_delay_min": 6.34,
        "median_delay_min": 5.39,
        "p90_delay_min": 11.4,
        "p95_delay_min": 13.94,
        "std_delay_min": 3.17,
        "on_time_rate": 0.894,
        "delay_probability": 0.067
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "wind",
        "time_bucket": "evening_rush",
        "sample_count": 142,
        "mean_delay_min": 15.07,
        "median_delay_min": 12.81,
        "p90_delay_min": 27.13,
        "p95_delay_min": 33.15,
        "std_delay_min": 7.54,
        "on_time_rate": 0.749,
        "delay_probability": 0.067
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "wind",
        "time_bucket": "night",
        "sample_count": 153,
        "mean_delay_min": 4.62,
        "median_delay_min": 3.93,
        "p90_delay_min": 8.32,
        "p95_delay_min": 10.17,
        "std_delay_min": 2.31,
        "on_time_rate": 0.923,
        "delay_probability": 0.067
    },
    {
        "road_type": "highway",
        "traffic_level": "low",
        "weather_condition": "wind",
        "time_bucket": "early_morning",
        "sample_count": 481,
        "mean_delay_min": 5.69,
        "median_delay_min": 4.84,
        "p90_delay_min": 10.24,
        "p95_delay_min": 12.52,
        "std_delay_min": 2.84,
        "on_time_rate": 0.905,
        "delay_probability": 0.067
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "clear",
        "time_bucket": "morning_rush",
        "sample_count": 234,
        "mean_delay_min": 17.91,
        "median_delay_min": 15.22,
        "p90_delay_min": 32.23,
        "p95_delay_min": 39.4,
        "std_delay_min": 8.95,
        "on_time_rate": 0.702,
        "delay_probability": 0.083
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "clear",
        "time_bucket": "midday",
        "sample_count": 278,
        "mean_delay_min": 5.73,
        "median_delay_min": 4.87,
        "p90_delay_min": 10.31,
        "p95_delay_min": 12.61,
        "std_delay_min": 2.87,
        "on_time_rate": 0.904,
        "delay_probability": 0.083
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "clear",
        "time_bucket": "evening_rush",
        "sample_count": 207,
        "mean_delay_min": 15.28,
        "median_delay_min": 12.99,
        "p90_delay_min": 27.51,
        "p95_delay_min": 33.62,
        "std_delay_min": 7.64,
        "on_time_rate": 0.745,
        "delay_probability": 0.083
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "clear",
        "time_bucket": "night",
        "sample_count": 169,
        "mean_delay_min": 5.92,
        "median_delay_min": 5.03,
        "p90_delay_min": 10.65,
        "p95_delay_min": 13.02,
        "std_delay_min": 2.96,
        "on_time_rate": 0.901,
        "delay_probability": 0.083
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "clear",
        "time_bucket": "early_morning",
        "sample_count": 38,
        "mean_delay_min": 5.42,
        "median_delay_min": 4.6,
        "p90_delay_min": 9.75,
        "p95_delay_min": 11.91,
        "std_delay_min": 2.71,
        "on_time_rate": 0.91,
        "delay_probability": 0.083
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "cloudy",
        "time_bucket": "morning_rush",
        "sample_count": 329,
        "mean_delay_min": 13.08,
        "median_delay_min": 11.12,
        "p90_delay_min": 23.54,
        "p95_delay_min": 28.78,
        "std_delay_min": 6.54,
        "on_time_rate": 0.782,
        "delay_probability": 0.1
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "cloudy",
        "time_bucket": "midday",
        "sample_count": 231,
        "mean_delay_min": 6.29,
        "median_delay_min": 5.34,
        "p90_delay_min": 11.32,
        "p95_delay_min": 13.83,
        "std_delay_min": 3.14,
        "on_time_rate": 0.895,
        "delay_probability": 0.1
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "cloudy",
        "time_bucket": "evening_rush",
        "sample_count": 485,
        "mean_delay_min": 17.06,
        "median_delay_min": 14.5,
        "p90_delay_min": 30.71,
        "p95_delay_min": 37.54,
        "std_delay_min": 8.53,
        "on_time_rate": 0.716,
        "delay_probability": 0.1
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "cloudy",
        "time_bucket": "night",
        "sample_count": 468,
        "mean_delay_min": 5.87,
        "median_delay_min": 4.99,
        "p90_delay_min": 10.57,
        "p95_delay_min": 12.92,
        "std_delay_min": 2.94,
        "on_time_rate": 0.902,
        "delay_probability": 0.1
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "cloudy",
        "time_bucket": "early_morning",
        "sample_count": 412,
        "mean_delay_min": 9.77,
        "median_delay_min": 8.31,
        "p90_delay_min": 17.59,
        "p95_delay_min": 21.5,
        "std_delay_min": 4.89,
        "on_time_rate": 0.837,
        "delay_probability": 0.1
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "rain",
        "time_bucket": "morning_rush",
        "sample_count": 236,
        "mean_delay_min": 20.43,
        "median_delay_min": 17.37,
        "p90_delay_min": 36.78,
        "p95_delay_min": 44.95,
        "std_delay_min": 10.22,
        "on_time_rate": 0.659,
        "delay_probability": 0.167
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "rain",
        "time_bucket": "midday",
        "sample_count": 100,
        "mean_delay_min": 13.47,
        "median_delay_min": 11.45,
        "p90_delay_min": 24.25,
        "p95_delay_min": 29.63,
        "std_delay_min": 6.74,
        "on_time_rate": 0.775,
        "delay_probability": 0.167
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "rain",
        "time_bucket": "evening_rush",
        "sample_count": 54,
        "mean_delay_min": 22.4,
        "median_delay_min": 19.04,
        "p90_delay_min": 40.33,
        "p95_delay_min": 49.29,
        "std_delay_min": 11.2,
        "on_time_rate": 0.627,
        "delay_probability": 0.167
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "rain",
        "time_bucket": "night",
        "sample_count": 413,
        "mean_delay_min": 9.44,
        "median_delay_min": 8.03,
        "p90_delay_min": 17.0,
        "p95_delay_min": 20.78,
        "std_delay_min": 4.72,
        "on_time_rate": 0.843,
        "delay_probability": 0.167
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "rain",
        "time_bucket": "early_morning",
        "sample_count": 386,
        "mean_delay_min": 13.97,
        "median_delay_min": 11.87,
        "p90_delay_min": 25.14,
        "p95_delay_min": 30.73,
        "std_delay_min": 6.98,
        "on_time_rate": 0.767,
        "delay_probability": 0.167
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "snow",
        "time_bucket": "morning_rush",
        "sample_count": 183,
        "mean_delay_min": 30.37,
        "median_delay_min": 25.81,
        "p90_delay_min": 54.66,
        "p95_delay_min": 66.81,
        "std_delay_min": 15.18,
        "on_time_rate": 0.494,
        "delay_probability": 0.333
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "snow",
        "time_bucket": "midday",
        "sample_count": 62,
        "mean_delay_min": 20.75,
        "median_delay_min": 17.64,
        "p90_delay_min": 37.35,
        "p95_delay_min": 45.65,
        "std_delay_min": 10.37,
        "on_time_rate": 0.654,
        "delay_probability": 0.333
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "snow",
        "time_bucket": "evening_rush",
        "sample_count": 383,
        "mean_delay_min": 29.07,
        "median_delay_min": 24.71,
        "p90_delay_min": 52.33,
        "p95_delay_min": 63.96,
        "std_delay_min": 14.54,
        "on_time_rate": 0.515,
        "delay_probability": 0.333
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "snow",
        "time_bucket": "night",
        "sample_count": 301,
        "mean_delay_min": 23.75,
        "median_delay_min": 20.19,
        "p90_delay_min": 42.74,
        "p95_delay_min": 52.24,
        "std_delay_min": 11.87,
        "on_time_rate": 0.604,
        "delay_probability": 0.333
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "snow",
        "time_bucket": "early_morning",
        "sample_count": 208,
        "mean_delay_min": 20.86,
        "median_delay_min": 17.73,
        "p90_delay_min": 37.55,
        "p95_delay_min": 45.9,
        "std_delay_min": 10.43,
        "on_time_rate": 0.652,
        "delay_probability": 0.333
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "fog",
        "time_bucket": "morning_rush",
        "sample_count": 408,
        "mean_delay_min": 23.39,
        "median_delay_min": 19.88,
        "p90_delay_min": 42.09,
        "p95_delay_min": 51.45,
        "std_delay_min": 11.69,
        "on_time_rate": 0.61,
        "delay_probability": 0.217
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "fog",
        "time_bucket": "midday",
        "sample_count": 379,
        "mean_delay_min": 14.07,
        "median_delay_min": 11.96,
        "p90_delay_min": 25.33,
        "p95_delay_min": 30.96,
        "std_delay_min": 7.04,
        "on_time_rate": 0.765,
        "delay_probability": 0.217
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "fog",
        "time_bucket": "evening_rush",
        "sample_count": 286,
        "mean_delay_min": 23.55,
        "median_delay_min": 20.02,
        "p90_delay_min": 42.39,
        "p95_delay_min": 51.81,
        "std_delay_min": 11.78,
        "on_time_rate": 0.607,
        "delay_probability": 0.217
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "fog",
        "time_bucket": "night",
        "sample_count": 51,
        "mean_delay_min": 12.19,
        "median_delay_min": 10.37,
        "p90_delay_min": 21.95,
        "p95_delay_min": 26.83,
        "std_delay_min": 6.1,
        "on_time_rate": 0.797,
        "delay_probability": 0.217
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "fog",
        "time_bucket": "early_morning",
        "sample_count": 73,
        "mean_delay_min": 17.16,
        "median_delay_min": 14.58,
        "p90_delay_min": 30.88,
        "p95_delay_min": 37.74,
        "std_delay_min": 8.58,
        "on_time_rate": 0.714,
        "delay_probability": 0.217
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "wind",
        "time_bucket": "morning_rush",
        "sample_count": 212,
        "mean_delay_min": 20.79,
        "median_delay_min": 17.67,
        "p90_delay_min": 37.42,
        "p95_delay_min": 45.74,
        "std_delay_min": 10.39,
        "on_time_rate": 0.654,
        "delay_probability": 0.133
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "wind",
        "time_bucket": "midday",
        "sample_count": 399,
        "mean_delay_min": 14.2,
        "median_delay_min": 12.07,
        "p90_delay_min": 25.56,
        "p95_delay_min": 31.25,
        "std_delay_min": 7.1,
        "on_time_rate": 0.763,
        "delay_probability": 0.133
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "wind",
        "time_bucket": "evening_rush",
        "sample_count": 431,
        "mean_delay_min": 20.54,
        "median_delay_min": 17.46,
        "p90_delay_min": 36.98,
        "p95_delay_min": 45.19,
        "std_delay_min": 10.27,
        "on_time_rate": 0.658,
        "delay_probability": 0.133
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "wind",
        "time_bucket": "night",
        "sample_count": 366,
        "mean_delay_min": 7.52,
        "median_delay_min": 6.39,
        "p90_delay_min": 13.54,
        "p95_delay_min": 16.55,
        "std_delay_min": 3.76,
        "on_time_rate": 0.875,
        "delay_probability": 0.133
    },
    {
        "road_type": "highway",
        "traffic_level": "moderate",
        "weather_condition": "wind",
        "time_bucket": "early_morning",
        "sample_count": 155,
        "mean_delay_min": 12.03,
        "median_delay_min": 10.22,
        "p90_delay_min": 21.65,
        "p95_delay_min": 26.46,
        "std_delay_min": 6.01,
        "on_time_rate": 0.8,
        "delay_probability": 0.133
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "clear",
        "time_bucket": "morning_rush",
        "sample_count": 374,
        "mean_delay_min": 24.48,
        "median_delay_min": 20.81,
        "p90_delay_min": 44.06,
        "p95_delay_min": 53.86,
        "std_delay_min": 12.24,
        "on_time_rate": 0.592,
        "delay_probability": 0.25
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "clear",
        "time_bucket": "midday",
        "sample_count": 204,
        "mean_delay_min": 21.12,
        "median_delay_min": 17.95,
        "p90_delay_min": 38.02,
        "p95_delay_min": 46.47,
        "std_delay_min": 10.56,
        "on_time_rate": 0.648,
        "delay_probability": 0.25
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "clear",
        "time_bucket": "evening_rush",
        "sample_count": 311,
        "mean_delay_min": 23.97,
        "median_delay_min": 20.38,
        "p90_delay_min": 43.15,
        "p95_delay_min": 52.74,
        "std_delay_min": 11.99,
        "on_time_rate": 0.6,
        "delay_probability": 0.25
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "clear",
        "time_bucket": "night",
        "sample_count": 498,
        "mean_delay_min": 14.11,
        "median_delay_min": 11.99,
        "p90_delay_min": 25.4,
        "p95_delay_min": 31.04,
        "std_delay_min": 7.06,
        "on_time_rate": 0.765,
        "delay_probability": 0.25
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "clear",
        "time_bucket": "early_morning",
        "sample_count": 123,
        "mean_delay_min": 15.92,
        "median_delay_min": 13.53,
        "p90_delay_min": 28.65,
        "p95_delay_min": 35.02,
        "std_delay_min": 7.96,
        "on_time_rate": 0.735,
        "delay_probability": 0.25
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "cloudy",
        "time_bucket": "morning_rush",
        "sample_count": 141,
        "mean_delay_min": 28.6,
        "median_delay_min": 24.31,
        "p90_delay_min": 51.47,
        "p95_delay_min": 62.91,
        "std_delay_min": 14.3,
        "on_time_rate": 0.523,
        "delay_probability": 0.267
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "cloudy",
        "time_bucket": "midday",
        "sample_count": 219,
        "mean_delay_min": 18.78,
        "median_delay_min": 15.97,
        "p90_delay_min": 33.81,
        "p95_delay_min": 41.32,
        "std_delay_min": 9.39,
        "on_time_rate": 0.687,
        "delay_probability": 0.267
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "cloudy",
        "time_bucket": "evening_rush",
        "sample_count": 358,
        "mean_delay_min": 27.58,
        "median_delay_min": 23.45,
        "p90_delay_min": 49.65,
        "p95_delay_min": 60.68,
        "std_delay_min": 13.79,
        "on_time_rate": 0.54,
        "delay_probability": 0.267
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "cloudy",
        "time_bucket": "night",
        "sample_count": 177,
        "mean_delay_min": 19.24,
        "median_delay_min": 16.35,
        "p90_delay_min": 34.63,
        "p95_delay_min": 42.33,
        "std_delay_min": 9.62,
        "on_time_rate": 0.679,
        "delay_probability": 0.267
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "cloudy",
        "time_bucket": "early_morning",
        "sample_count": 31,
        "mean_delay_min": 17.12,
        "median_delay_min": 14.55,
        "p90_delay_min": 30.82,
        "p95_delay_min": 37.67,
        "std_delay_min": 8.56,
        "on_time_rate": 0.715,
        "delay_probability": 0.267
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "rain",
        "time_bucket": "morning_rush",
        "sample_count": 342,
        "mean_delay_min": 31.44,
        "median_delay_min": 26.72,
        "p90_delay_min": 56.59,
        "p95_delay_min": 69.16,
        "std_delay_min": 15.72,
        "on_time_rate": 0.476,
        "delay_probability": 0.333
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "rain",
        "time_bucket": "midday",
        "sample_count": 41,
        "mean_delay_min": 25.82,
        "median_delay_min": 21.95,
        "p90_delay_min": 46.47,
        "p95_delay_min": 56.8,
        "std_delay_min": 12.91,
        "on_time_rate": 0.57,
        "delay_probability": 0.333
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "rain",
        "time_bucket": "evening_rush",
        "sample_count": 455,
        "mean_delay_min": 30.4,
        "median_delay_min": 25.84,
        "p90_delay_min": 54.73,
        "p95_delay_min": 66.89,
        "std_delay_min": 15.2,
        "on_time_rate": 0.493,
        "delay_probability": 0.333
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "rain",
        "time_bucket": "night",
        "sample_count": 371,
        "mean_delay_min": 23.47,
        "median_delay_min": 19.95,
        "p90_delay_min": 42.24,
        "p95_delay_min": 51.63,
        "std_delay_min": 11.73,
        "on_time_rate": 0.609,
        "delay_probability": 0.333
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "rain",
        "time_bucket": "early_morning",
        "sample_count": 318,
        "mean_delay_min": 22.88,
        "median_delay_min": 19.45,
        "p90_delay_min": 41.18,
        "p95_delay_min": 50.33,
        "std_delay_min": 11.44,
        "on_time_rate": 0.619,
        "delay_probability": 0.333
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "snow",
        "time_bucket": "morning_rush",
        "sample_count": 81,
        "mean_delay_min": 40.25,
        "median_delay_min": 34.21,
        "p90_delay_min": 72.45,
        "p95_delay_min": 88.55,
        "std_delay_min": 20.13,
        "on_time_rate": 0.329,
        "delay_probability": 0.5
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "snow",
        "time_bucket": "midday",
        "sample_count": 63,
        "mean_delay_min": 33.19,
        "median_delay_min": 28.21,
        "p90_delay_min": 59.75,
        "p95_delay_min": 73.02,
        "std_delay_min": 16.6,
        "on_time_rate": 0.447,
        "delay_probability": 0.5
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "snow",
        "time_bucket": "evening_rush",
        "sample_count": 221,
        "mean_delay_min": 40.59,
        "median_delay_min": 34.5,
        "p90_delay_min": 73.07,
        "p95_delay_min": 89.3,
        "std_delay_min": 20.3,
        "on_time_rate": 0.323,
        "delay_probability": 0.5
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "snow",
        "time_bucket": "night",
        "sample_count": 108,
        "mean_delay_min": 32.01,
        "median_delay_min": 27.21,
        "p90_delay_min": 57.61,
        "p95_delay_min": 70.42,
        "std_delay_min": 16.0,
        "on_time_rate": 0.467,
        "delay_probability": 0.5
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "snow",
        "time_bucket": "early_morning",
        "sample_count": 382,
        "mean_delay_min": 29.94,
        "median_delay_min": 25.45,
        "p90_delay_min": 53.89,
        "p95_delay_min": 65.87,
        "std_delay_min": 14.97,
        "on_time_rate": 0.501,
        "delay_probability": 0.5
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "fog",
        "time_bucket": "morning_rush",
        "sample_count": 79,
        "mean_delay_min": 34.55,
        "median_delay_min": 29.37,
        "p90_delay_min": 62.2,
        "p95_delay_min": 76.02,
        "std_delay_min": 17.28,
        "on_time_rate": 0.424,
        "delay_probability": 0.383
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "fog",
        "time_bucket": "midday",
        "sample_count": 339,
        "mean_delay_min": 28.47,
        "median_delay_min": 24.2,
        "p90_delay_min": 51.24,
        "p95_delay_min": 62.62,
        "std_delay_min": 14.23,
        "on_time_rate": 0.526,
        "delay_probability": 0.383
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "fog",
        "time_bucket": "evening_rush",
        "sample_count": 203,
        "mean_delay_min": 32.44,
        "median_delay_min": 27.58,
        "p90_delay_min": 58.4,
        "p95_delay_min": 71.37,
        "std_delay_min": 16.22,
        "on_time_rate": 0.459,
        "delay_probability": 0.383
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "fog",
        "time_bucket": "night",
        "sample_count": 81,
        "mean_delay_min": 24.01,
        "median_delay_min": 20.41,
        "p90_delay_min": 43.21,
        "p95_delay_min": 52.81,
        "std_delay_min": 12.0,
        "on_time_rate": 0.6,
        "delay_probability": 0.383
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "fog",
        "time_bucket": "early_morning",
        "sample_count": 171,
        "mean_delay_min": 25.34,
        "median_delay_min": 21.54,
        "p90_delay_min": 45.61,
        "p95_delay_min": 55.75,
        "std_delay_min": 12.67,
        "on_time_rate": 0.578,
        "delay_probability": 0.383
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "wind",
        "time_bucket": "morning_rush",
        "sample_count": 121,
        "mean_delay_min": 27.64,
        "median_delay_min": 23.49,
        "p90_delay_min": 49.75,
        "p95_delay_min": 60.81,
        "std_delay_min": 13.82,
        "on_time_rate": 0.539,
        "delay_probability": 0.3
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "wind",
        "time_bucket": "midday",
        "sample_count": 374,
        "mean_delay_min": 23.32,
        "median_delay_min": 19.82,
        "p90_delay_min": 41.98,
        "p95_delay_min": 51.3,
        "std_delay_min": 11.66,
        "on_time_rate": 0.611,
        "delay_probability": 0.3
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "wind",
        "time_bucket": "evening_rush",
        "sample_count": 294,
        "mean_delay_min": 31.46,
        "median_delay_min": 26.74,
        "p90_delay_min": 56.64,
        "p95_delay_min": 69.22,
        "std_delay_min": 15.73,
        "on_time_rate": 0.476,
        "delay_probability": 0.3
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "wind",
        "time_bucket": "night",
        "sample_count": 202,
        "mean_delay_min": 20.64,
        "median_delay_min": 17.54,
        "p90_delay_min": 37.15,
        "p95_delay_min": 45.41,
        "std_delay_min": 10.32,
        "on_time_rate": 0.656,
        "delay_probability": 0.3
    },
    {
        "road_type": "highway",
        "traffic_level": "high",
        "weather_condition": "wind",
        "time_bucket": "early_morning",
        "sample_count": 273,
        "mean_delay_min": 17.9,
        "median_delay_min": 15.22,
        "p90_delay_min": 32.23,
        "p95_delay_min": 39.39,
        "std_delay_min": 8.95,
        "on_time_rate": 0.702,
        "delay_probability": 0.3
    },
    {
        "road_type": "highway",
        "traffic_level": "congested",
        "weather_condition": "clear",
        "time_bucket": "morning_rush",
        "sample_count": 257,
        "mean_delay_min": 44.04,
        "median_delay_min": 37.43,
        "p90_delay_min": 79.27,
        "p95_delay_min": 96.89,
        "std_delay_min": 22.02,
        "on_time_rate": 0.266,
        "delay_probability": 0.583
    },
    {
        "road_type": "highway",
        "traffic_level": "congested",
        "weather_condition": "clear",
        "time_bucket": "midday",
        "sample_count": 224,
        "mean_delay_min": 40.46,
        "median_delay_min": 34.39,
        "p90_delay_min": 72.83,
        "p95_delay_min": 89.01,
        "std_delay_min": 20.23,
        "on_time_rate": 0.326,
        "delay_probability": 0.583
    },
    {
        "road_type": "highway",
        "traffic_level": "congested",
        "weather_condition": "clear",
        "time_bucket": "evening_rush",
        "sample_count": 328,
        "mean_delay_min": 49.29,
        "median_delay_min": 41.89,
        "p90_delay_min": 88.71,
        "p95_delay_min": 108.43,
        "std_delay_min": 24.64,
        "on_time_rate": 0.179,
        "delay_probability": 0.583
    },
    {
        "road_type": "highway",
        "traffic_level": "congested",
        "weather_condition": "clear",
        "time_bucket": "night",
        "sample_count": 276,
        "mean_delay_min": 33.13,
        "median_delay_min": 28.16,
        "p90_delay_min": 59.64,
        "p95_delay_min": 72.89,
        "std_delay_min": 16.57,
        "on_time_rate": 0.448,
        "delay_probability": 0.583
    },
    {
        "road_type": "highway",
        "traffic_level": "congested",
        "weather_condition": "clear",
        "time_bucket": "early_morning",
        "sample_count": 196,
        "mean_delay_min": 35.12,
        "median_delay_min": 29.85,
        "p90_delay_min": 63.22,
        "p95_delay_min": 77.27,
        "std_delay_min": 17.56,
        "on_time_rate": 0.415,
        "delay_probability": 0.583
    },
    {
        "road_type": "highway",
        "traffic_level": "congested",
        "weather_condition": "cloudy",
        "time_bucket": "morning_rush",
        "sample_count": 343,
        "mean_delay_min": 43.84,
        "median_delay_min": 37.27,
        "p90_delay_min": 78.92,
        "p95_delay_min": 96.46,
        "std_delay_min": 21.92,
        "on_time_rate": 0.269,
        "delay_probability": 0.6
    },
    {
        "road_type": "highway",
        "traffic_level": "congested",
        "weather_condition": "cloudy",
        "time_bucket": "midday",
        "sample_count": 436,
        "mean_delay_min": 40.96,
        "median_delay_min": 34.81,
        "p90_delay_min": 73.73,
        "p95_delay_min": 90.11,
        "std_delay_min": 20.48,
        "on_time_rate": 0.317,
        "delay_probability": 0.6
    },
    {
        "road_type": "highway",
        "traffic_level": "congested",
        "weather_condition": "cloudy",
        "time_bucket": "evening_rush",
        "sample_count": 356,
        "mean_delay_min": 49.85,
        "median_delay_min": 42.37,
        "p90_delay_min": 89.73,
        "p95_delay_min": 109.66,
        "std_delay_min": 24.92,
        "on_time_rate": 0.169,
        "delay_probability": 0.6
    },
    {
        "road_type": "highway",
        "traffic_level": "congested",
        "weather_condition": "cloudy",
        "time_bucket": "night",
        "sample_count": 143,
        "mean_delay_min": 40.89,
        "median_delay_min": 34.75,
        "p90_delay_min": 73.6,
        "p95_delay_min": 89.95,
        "std_delay_min": 20.44,
        "on_time_rate": 0.319,
        "delay_probability": 0.6
    },
    {
        "road_type": "highway",
        "traffic_level": "congested",
        "weather_condition": "cloudy",
        "time_bucket": "early_morning",
        "sample_count": 251,
        "mean_delay_min": 37.76,
        "median_delay_min": 32.1,
        "p90_delay_min": 67.97,
        "p95_delay_min": 83.07,
        "std_delay_min": 18.88,
        "on_time_rate": 0.371,
        "delay_probability": 0.6
    }
]
};
